# Generated by Django 5.0.7 on 2024-08-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Snakers', '0002_zapatilla_talle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapatilla_talle',
            old_name='zapatilla_talle',
            new_name='zapatilla',
        ),
    ]
