# Generated by Django 5.0.7 on 2024-08-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snakers', '0003_rename_zapatilla_talle_zapatilla_talle_zapatilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla_talle',
            name='zapatilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='Snakers.zapatillas'),
        ),
    ]
