# Generated by Django 5.0.7 on 2024-08-01 21:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snakers', '0004_alter_zapatilla_talle_zapatilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapatilla_Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('fecha', models.DateField(default=datetime.datetime(2024, 8, 1, 18, 4, 24, 199411))),
                ('zapatilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='Snakers.zapatillas')),
            ],
        ),
    ]
