# Generated by Django 5.0.7 on 2024-08-01 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snakers', '0005_zapatilla_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zapatilla_precio',
            old_name='zapatilla',
            new_name='zapatilla_precio',
        ),
        migrations.RenameField(
            model_name='zapatilla_talle',
            old_name='zapatilla',
            new_name='zapatilla_talle',
        ),
        migrations.AlterField(
            model_name='zapatilla_precio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 18, 6, 52, 939742)),
        ),
    ]
