# Generated by Django 5.0.7 on 2024-08-01 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snakers', '0006_rename_zapatilla_zapatilla_precio_zapatilla_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla_precio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 8, 1, 18, 7, 16, 124752)),
        ),
    ]
