# Generated by Django 5.0.7 on 2024-08-01 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Snakers', '0007_alter_zapatilla_precio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapatilla_precio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 18, 12, 2, 614346)),
        ),
    ]
